### ISSUE TITLE
HVAC controls do not work

### ISSUE THREAD

**Issue by alexanderfitu** [hacf-fr/hassRenaultZE#103]
When selecting HVAC from OFF to heat/cool, it reverts back to off after 5 seconds, without apparently doing anything. 

Setting the temperature does the same (but this is not available in the app so I would not expect this to work).

The logs do not produce anything when selecting the options, even with:

  logs:
     renault: debug

**Comment by lonebaggie** [comment]
Works for my ZE40.  HVAC reverts back to off almost immediately  but does trigger the Zoe's  Air-con .  Would be nice if the HVAC would stay on until the air-con completes but I suspect the issue is with the Renault Servers

**Comment by alexanderfitu** [comment]
Apologies, This can be closed. The car was parked in a location with no signal, and without feedback, its impossible to know if the issue was with the car or with the command not being sent :)
