### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by flouck** [hacf-fr/hassRenaultZE#106]
## Describe the bug
An error appears frequently in my log. Anyone facing similar issue?

## Debug log

```
Logger: custom_components.renault.renault_vehicle
Source: helpers/update_coordinator.py:166
Integration: Renault (documentation, issues)
First occurred: 6:29:41 PM (1 occurrences)
Last logged: 6:29:41 PM
Error fetching VF1xxxxxxxxx battery data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.') 
```

**Comment by epenet** [comment]
That is a temporary error on the Renault side (it seems to be an error between their internet-facing servers and the backend servers) - there's nothing we can really do about it.
