### ISSUE TITLE
Could we add test coverage?

### ISSUE THREAD

**Issue by epenet** [hacf-fr/hassRenaultZE#119]
Issue #117 could probably have been avoided with automatic testing and type checking.
Maybe this could be used?
https://community.home-assistant.io/t/pytest-homeassistant-custom-component/227477

**Comment by epenet** [comment]
@oncleben31 I see that you have participated in https://github.com/custom-components/integration_blueprint/pull/50.
Do you wish to do the honours?

**Comment by oncleben31** [comment]
mission accepted.

**Comment by epenet** [comment]
Work started on #134
