### ISSUE TITLE
It's impossible to log in to the Renault account, in order to install the Integration

### ISSUE THREAD

**Issue by mago-kamar** [hacf-fr/hassRenaultZE#127]
Sorry, but I've not log to attach because I'm not albe to install the integration due to an Error Replied, even if they are valid, in fact I can login to Renaul site.

Here the HA versions:
Operating System Home Assistant OS 5.10 
Version supervisor-2021.01.7 
Version core-2021.2.1

In the integration page, I click on add button, and the on Renault.
I answer to 'locale' choosing it_IT and then I instert my email and password, but the answer is always the same ... 'UNKNOW ERROR OCCURED'.

Can you help me, please?

Thank you very much

Enrico

**Comment by epenet** [comment]
There is really not enough information to help you.
Please ensure that you have enabled logging using the instructions on: https://github.com/hacf-fr/hassRenaultZE#logging, and that you are using the latest release (v3.0.6)

Then try again and provide logs.

**Comment by mago-kamar** [comment]
Hello @epenet ,
I had an old version ... I installed the last one, and now it works fine.

Thank you very much, and best regards.

Enrico
