### ISSUE TITLE
Incompatible with Onvif integration?

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#129]
Home assistant is well connected but after several reboots it no longer wants to work for Zoe

![image](https://user-images.githubusercontent.com/41892950/108622641-71bbf280-743a-11eb-94b4-2114c2a174ea.jpeg)

**Comment by epenet** [comment]
If you want some help you need to provide lots more details...
Version? Error details? Logs? Etc.

**Comment by JeedHome44** [comment]
Now I have this: all work but no battery pourcent and calendar

**Comment by JeedHome44** [comment]
I just add an Onvif camera in Hassio. If I delete it, all work with Renault ZE. If I add Onvif camera, this error came back... it's very strange...

**Comment by JeedHome44** [comment]
Onvif and RenaultZE use same port with docker?

**Comment by epenet** [comment]
If you want some help you need to provide lots more details...
Version? Error details? Logs? Etc.

**Comment by JeedHome44** [comment]
I do not know what to give you but if I put Onvif, RenaultZE does not work completely.

**Comment by JeedHome44** [comment]
I was told on facebook that the problem surely stems from the docker ports which must be the same for Onvif and RenaultZE.  Is it possible to verify?

**Comment by epenet** [comment]
I find myself repeating myself: you don't provide version number, you don't provide error messages, you don't provide logs or traces. In such conditions no-one will be able to help you...

There is some documentation on the home page to enable deeper traces: https://github.com/hacf-fr/hassRenaultZE#logging

**Comment by JeedHome44** [comment]
Hello,

I use last version of Renault ZE Integration.
I have no error message but if i activate Onvif integration, all sensor RenaultZE brake...
how do i know which port is using RenaultZE?

I don't know how to use logs.
I just know that Renault ZE works as soon as I remove the Onvif integration
if I put Onvif back, RenaultZE displays everything as Unavailable

I was told it was probably a port problem.
The 2 integrations must use the same ports.
How do I know which port uses RenaultZE and Onvif?

**Comment by epenet** [comment]
You should ask for help to setup logging on the general Home Assistant forums.
Once you have enabled logging, then we can look in more details at your issue.

Regarding docker ports, the Renault integration doesn't use any incoming ports so I very much doubt it is a Docker port issue...

**Comment by epenet** [comment]
@JeedHome44 did you manage to enable logging on your HA setup?

**Comment by JeedHome44** [comment]
now it works with Onvif.  I did 1 reboot of my Raspberry and after that it worked.  I don't know why it did this at first.  this problem is therefore closed.  thank you
