### ISSUE TITLE
HACS report "Repository is deleted"

### ISSUE THREAD

**Issue by massiant70** [hacf-fr/hassRenaultZE#130]
hacf-fr/hassRenaultZE - Repository is in the blacklist.

**Comment by epenet** [comment]
Hopefully fixed with #131

**Comment by epenet** [comment]
@massiant70 can you please confirm which blacklist you are referring to, and whether this fixes it?

**Comment by epenet** [comment]
@oncleben31 is this linked to recent changes on hacf-fr private/public?

**Comment by epenet** [comment]
It seems to have been removed following discussions on : https://community.home-assistant.io/t/error-on-hacs-with-renaut-zoe/288712

This is the offending commit: https://github.com/hacs/default/commit/b8da843f00ceeab604a99fe128d40d7749efdee0

**Comment by massiant70** [comment]
> @massiant70 can you please confirm which blacklist you are referring to, and whether this fixes it?

HACS (ERROR)
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:48
Integration: HACS (documentation, issues)
First occurred: 15:36:02 (1 occurrences)
Last logged: 15:36:02

hacf-fr/hassRenaultZE - Repository is in the blacklist.

HACS (WARNING)
Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/hacs.py:319
Integration: HACS (documentation, issues)
First occurred: 15:36:02 (1 occurrences)
Last logged: 15:36:02

You have hacf-fr/hassRenaultZE installed with HACS this repository has been removed, please consider removing it. Removal reason (remove)

**Comment by epenet** [comment]
Thanks for the input. It seems that GitHub mistakenly deactivated the hacf-fr account earlier this week, and the HACS maintainter was very quick to disable it.

A new PR has been created on HACS to reactivate it: https://github.com/hacs/default/pull/860

**Comment by massiant70** [comment]
> Thanks for the input. It seems that GitHub mistakenly deactivated the hacf-fr account earlier this week, and the HACS maintainter was very quick to disable it.

It seems that the HACS maintainer is not so quick to re-enable it. 
I still get in blacklist and error message.
Keep on wait.

**Comment by massiant70** [comment]
Well I don't know what's going on, but still got the message error about this repository.

**Comment by epenet** [comment]
If you want to know when it will be active again - there is a "subscribe" option on the HACS PullRequest: hacs/default#860
But all we can do here on hassRenaultZE is wait for HACS...

**Comment by epenet** [comment]
Hi @massiant70 
It seems the HACS PR has just now been merged.
Can you please confirm that the message has disappeared?

**Comment by massiant70** [comment]
YESSS !!!! I can confirm it !!!!
Thank you very much !!!
