### ISSUE TITLE
charge_set_schedules documentation

### ISSUE THREAD

**Issue by eviollet** [hacf-fr/hassRenaultZE#140]
Hi.

This is more a question than a bug. 
I can't seem to find documentation concerning the "charge_set_schedules" implementation.
The default usage indicates that it is possible to change the schedule of a single id and that is working fine
However, I'm looking for a way to change multiple schedule ids in just one call. Is this possible?
If not, could it be looked into for a future version?

In advance, thanks.

**Comment by epenet** [comment]
Currently it is not possible, and it's not something I have time to work on at the moment.

It may be possible to accept both a `dict` and a `list[dict]` in the [schema validation](https://github.com/hacf-fr/hassRenaultZE/blob/master/custom_components/renault/services.py#L49), and then [loop through the items](https://github.com/hacf-fr/hassRenaultZE/blob/master/custom_components/renault/services.py#L128) in the list before sending through to the Renault-API

I'm fully open to PR

**Comment by eviollet** [comment]
Thanks for the update.
I really need to dig into HA development. This seems like something that could be fun.

I'll keep you informed. :)

**Comment by epenet** [comment]
Hi @eviollet,

This has now been implemented in the HomeAssistant core: https://github.com/home-assistant/core/pull/54820
Sadly it didn't make it into 2021.09, but starting with HomeAssistant 2021.10, it will be possible to use either a single schedule, or a list of schedule.
