### ISSUE TITLE
italian translations

### ISSUE THREAD

**Issue by Giancky79** [hacf-fr/hassRenaultZE#148]
{
  "stato": {
    "renault__plug_state": {
      "unplugged": "Scollegato",
      "plugged": "Collegato",
      "plug_error": "Errore collegamento",
      "plug_unknown": "Collegamento sconosciuto"
    },
    "renault__stato_ricarica": {
      "not_in_charge": "Non in carica",
      "waiting_for_a_planned_charge": "In attesa del programma ricarica",
      "charge_ended": "Ricarica terminata",
      "waiting_for_current_charge": "In attesa di corrente per ricarica",
      "energy_flap_opened": "Sportello ricarica aperto",
      "charge_in_progress": "Ricarica",
      "charge_error": "Non in carica o Scollegato",
      "unavailable": "Non disponibile"
    },
    "renault__modalità_ricarica": {
      "always": "Istantaneo",
      "always_charging": "Istantaneo",
      "schedule_mode": "Programmato"
    }
  }
}

{
  "confi: {
    "abort": {
      "already_configured": "Account già configurato",
      "kamereon_no_account": "Impossibile trovare account Kamereon."
    },
    "error": {
      "invalid_credentials": "Credenziali invalide."
    },
    "step": {
      "kamereon": {
        "data": {
          "kamereon_account_id": "Account Kamereon"
        },
        "title": "Selezionare account Kamereon"
      },
      "user": {
        "data": {
          "locale": "Locale",
          "username": "Email",
          "password": "Password"
        },
        "title": "Credenziali Renault"
      }
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "scan_interval": "Tempo fra le 2 chiamate API",
          "distances_in_miles": "Mostra la distanza in miglia"
        }
      }
    }
  }
}

**Comment by VaguerOdin** [comment]
> {
> "stato": {
> "renault__plug_state": {
> "unplugged": "Scollegato",
> "plugged": "Collegato",
> "plug_error": "Errore collegamento",
> "plug_unknown": "Collegamento sconosciuto"
> },
> "renault__stato_ricarica": {
> "not_in_charge": "Non in carica",
> "waiting_for_a_planned_charge": "In attesa del programma ricarica",
> "charge_ended": "Ricarica terminata",
> "waiting_for_current_charge": "In attesa di corrente per ricarica",
> "energy_flap_opened": "Sportello ricarica aperto",
> "charge_in_progress": "Ricarica",
> "charge_error": "Non in carica o Scollegato",
> "unavailable": "Non disponibile"
> },
> "renault__modalità_ricarica": {
> "always": "Istantaneo",
> "always_charging": "Istantaneo",
> "schedule_mode": "Programmato"
> }
> }
> }

If I may say, the first part should be more correct this way translated:
```{
"stato": {
"renault__plug_state": {
"unplugged": "Scollegata",
"plugged": "Collegata",
"plug_error": "Errore collegamento",
"plug_unknown": "Collegamento sconosciuto"
},
"renault__stato_ricarica": {
"not_in_charge": "Non in carica",
"waiting_for_a_planned_charge": "In attesa della ricarica in programma",
"charge_ended": "Ricarica terminata",
"waiting_for_current_charge": "In attesa dell'attuale ricarica",
"energy_flap_opened": "Sportello di ricarica aperto",
"charge_in_progress": "In carica",
"charge_error": "Errore: Non in carica o scollegata",
"unavailable": "Non disponibile"
},
"renault__modalità_ricarica": {
"always": "Istantanea",
"always_charging": "Istantanea",
"schedule_mode": "Programmata"
}
}
}

Thank you

**Comment by epenet** [comment]
Thanks, but can you provide it as a Pull Request?
