### ISSUE TITLE
Install failed with "module 'marshmallow_dataclass' has no attribute 'class_schema'"

### ISSUE THREAD

**Issue by dasos** [hacf-fr/hassRenaultZE#150]
Hi, when I try to install the component, I get the stacktrace below, and an error saying "Config flow could not be loaded". I have previously had this component working well, but it stopped updating. I then removed it, and reinstalled via HACS. I have tried removing all renault_api related items in the deps directory. Anything else I can do? Thanks!

> 2021-07-25 11:28:48 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
>     resp = await self._request_handler(request)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 197, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
>     return await super().post(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
>     result = await method(view, request, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
>     result = await self._flow_mgr.async_init(
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
>     flow, result = await task
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
>     integration.get_platform("config_flow")
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/custom_components/renault/__init__.py", line 9, in <module>
>     from .renault_hub import RenaultHub
>   File "/config/custom_components/renault/renault_hub.py", line 11, in <module>
>     from renault_api.renault_account import RenaultAccount
>   File "/config/deps/lib/python3.9/site-packages/renault_api/renault_account.py", line 11, in <module>
>     from .kamereon import models
>   File "/config/deps/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 14, in <module>
>     from . import schemas
>   File "/config/deps/lib/python3.9/site-packages/renault_api/kamereon/schemas.py", line 8, in <module>
>     KamereonResponseSchema = marshmallow_dataclass.class_schema(
> AttributeError: module 'marshmallow_dataclass' has no attribute 'class_schema'

**Comment by epenet** [comment]
It looks like a dependency issue on marshmallow-dataclass. Are you able to check which version is installed?

**Comment by dasos** [comment]
Thanks for the response. Appears to be 8.4.1

> # find /config -name marshmallow_dataclass-*
> /config/deps/lib/python3.9/site-packages/marshmallow_dataclass-8.4.1.dist-info
> /config/deps/lib/python3.8/site-packages/marshmallow_dataclass-8.4.1.dist-info

**Comment by epenet** [comment]
as a quick test, can you downgrade it to v8.2.0?

**Comment by epenet** [comment]
Also, are you able to test the `renault-api` CLI?
https://github.com/hacf-fr/renault-api#cli-usage

**Comment by dasos** [comment]
Ahh. The latest release of the library is now [8.4.2](https://github.com/lovasoa/marshmallow_dataclass/releases/tag/v8.4.2),  and that promises Python 3.9 compatibility. (I'm using a container, and that is what is bundled.) And now it works. :) Thank you!
