### ISSUE TITLE
Ignore charge_mode when not supported

### ISSUE THREAD

**Issue by epenet** [hacf-fr/hassRenaultZE#56]
I have this error:
```
2020-10-18 00:28:26 ERROR (MainThread) [custom_components.renault.pyzevehicleproxy] Error requesting VF1AG_REDACTED charge_mode data: 403 Client Error: Forbidden for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/REDACTED/kamereon/kca/car-adapter/v1/cars/VF1AG_REDACTED /charge-mode?country=FR
```
Is it related to 'direct charge' or using schedule ? If yes this is normal. I 've the Life version and I think the option is not compatible with this Zoé version

_Originally posted by @oncleben31 in https://github.com/epenet/hassRenaultZE/issues/30#issuecomment-711090251_

**Comment by epenet** [comment]
There are three ways of looking at this:
- option 1 (easiest) is to simply disable the sensor in the entities list if your car doesn't support it
- option 2 is to use an "options flow" so that the user says "I don't have access to ZE interactive"
- option 3 would be to add the contracts lookup to pyze (see https://github.com/jamesremuscat/pyze/issues/84) and then work out which sensors should be created for which contract

**Comment by oncleben31** [comment]
What about trying to access the information during the initialisation of the integration ? If the service answer Error 403 the sensor is not added.

**Comment by epenet** [comment]
Should be implemented in #80

**Comment by epenet** [comment]
@oncleben31 are you happy to close this now that [release v3.0.2](https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2) is available?

**Comment by oncleben31** [comment]
Yes could be closed. Why do you keep it as an error in the log. It should be an info because we don't expect that the user open an issue or to make any correction for that.

**Comment by epenet** [comment]
We could change it to a warning...

**Comment by epenet** [comment]
@oncleben31 I looked at this but I would have to bypass the DataUpdateCoordinator on the first attempt - I think it is better to keep it as it is, and simply close this issue.
