### ISSUE TITLE
429 Too many requests

### ISSUE THREAD

**Issue by cris88** [hacf-fr/hassRenaultZE#68]
Hello,

I'm recently noticed on logs that renault api is giving me 429 HTTP Code, that corresponds to too many requests.
So, there is some kind of workarround tou fix this?

![image](https://user-images.githubusercontent.com/1536899/97642620-8d3f5f80-1a3d-11eb-8e8b-2dfaf907fff9.png)

Here the blank spaces on the graph is when the error occurrs.
![image](https://user-images.githubusercontent.com/1536899/97642659-a6e0a700-1a3d-11eb-8efd-f17c42782372.png)

Thanks!

**Comment by epenet** [comment]
As a quick fix, you can change the default scan interval in pyzevehicleproxy.py.
The current default is 60 seconds

DEFAULT_SCAN_INTERVAL = timedelta(seconds=60)

**Comment by cris88** [comment]
Thanks @epenet . The fix solve the issue (changed to 120 seconds). It's only me with this problem?

**Comment by oncleben31** [comment]
I have  already seen it. Mainly when developing in parallel on this custom component. So twice API request than normal usage. Perhaps we could decrease the refresh frequency to have some margin with concurrent usages: HA production, HA testor dev, mobile application and perhaps other I don't think about.

**Comment by PysX** [comment]
I can confirm that I have this problem too. I changed time interval to fixed it. I have a second environment that make calls to the Renault api, that could cause more requests to the Renault api.

**Comment by EricJanOud** [comment]
I have the same issue. I have the app running on my phone plus an iPad. I now also have HA pulling data, of course.
Detail: I also have two cars linked to my account - not sure if that means twice the polling requests, or just twice the data per request.
Anyway: I have set 120 seconds, and now we'll see. Will report back in a couple of hours with the result.
![unavailable](https://user-images.githubusercontent.com/16397878/97957268-feb73f00-1daa-11eb-91a3-d13dde10356a.png)

**Comment by EricJanOud** [comment]
I ended up using 5 minute polling intervals to get an uninterrupted data stream for both cars.
