### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by olivierfaber** [hacf-fr/hassRenaultZE#69]
When first configuring the component through the UI, I get the error "Invalid credentials."

Whilst I can login to https://my.renault.nl/ with the same credentials without any issue.

In the log there is this:

`2020-10-30 15:11:33 ERROR (MainThread) [custom_components.renault.pyzeproxy] Login to Gigya failed: Gigya returned error 403042: invalid loginID or password`

Im using version 3.0.0. Home Assistant version 0.117.0 (also checked 0.117.1). My locale is nl_NL. I used HACS to install the component.

**Comment by epenet** [comment]
Did you install the Renault application on your phone?
I believe the password for the Renault application is different to the one for the generic Renault website.

**Comment by olivierfaber** [comment]
Damn. You're absolutely right. The My Renault app is the correct account.
