### ISSUE TITLE
Do you want me to improve GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [hacf-fr/hassRenaultZE#71]
**Is your feature request related to a problem? Please describe.**
The only CI in here is Hassfest.

**Describe the solution you'd like**
I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Describe alternatives you've considered**
Closing this issue.

**Additional context**

**Comment by epenet** [comment]
Hi @KTibow 

We are looking to merge this custom_component into HA core (see https://github.com/home-assistant/core/pull/39605)
Once we manage this, this repository will become obsolete so it's probably not worth spending too much time on CI

**Comment by KTibow** [comment]
Okay. Thanks.

**Comment by oncleben31** [comment]
@KTibow I'm interested in your ideas for CI. I'm working in a cookiecutter template for HA custom component based on blueprint repository. If you want we can continue the discussion here: https://github.com/oncleben31/cookiecutter-homeassistant-custom-component

**Comment by KTibow** [comment]
See https://github.com/KTibow/ha-blueprint
