### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [hacf-fr/hassRenaultZE#72]
**Is your feature request related to a problem? Please describe.**
If you want, I can contribute some advanced CI to your repository in a PR. Right now it doesn't have any HACS or flake8, just hassfest.

**Describe the solution you'd like**
I can contribute some combined CI from https://KTibow/ha-blueprint#readme

**Describe alternatives you've considered**
I can also add some separate CI without relying on a 3rd party.

**Additional context**

**Comment by oncleben31** [comment]
Are you a bot ? #71

**Comment by KTibow** [comment]
Nope, I manually do this, but I do take advantage of the clipboard. It's kind of like when one person involved with HA dev raised a whole bunch of issues over at custom cards letting them know that they may need to improve their code for the latest version of HA. Apparently I'm dumb. I was just going over my saved notifications. Feel free to **delete** (not close this issue) because it's my fault.
