### ISSUE TITLE
Can't add integration in HA

### ISSUE THREAD

**Issue by ErnieB44** [hacf-fr/hassRenaultZE#76]
I'have followed the installation steps in the readme:
Copied all files to 'custom_components\renault' and when i try to add the integration by clicking the '+' and typing 'Renault' it cannot find the integration.
When looking in the manifest i find the url 'https://www.home-assistant.io/integrations/renault' for the documentation but this page does not exist.
I want to add the integration manually but i require all the settings for this component, can you please provide this?

**Comment by WinkelB** [comment]
Your restarted HA?

ErnieB44 <notifications@github.com> schrieb am Do., 19. Nov. 2020, 22:38:

**Comment by ErnieB44** [comment]
Yes.. i even rebooted the system

**Comment by WinkelB** [comment]
You often have to reload your browser cache so new integrations showing up.

Best is to try an incognito Tab
Hope that's help...

ErnieB44 <notifications@github.com> schrieb am Fr., 20. Nov. 2020, 05:42:

**Comment by ErnieB44** [comment]
Yes.. that did the trick. Stupid browser cache ;)
I can read out all of the data for my Renault Zoe.. however there is no device_tracker item, could it be because my car is doesn't support it, or should it always appear?

**Comment by epenet** [comment]
Location is not supported on Zoe phase 1 (Zoe22 / Zoe40)
For Zoe phase 2 (Zoe50), it should be available.

If you feel it should be available, you can always add always post your vehicle details (see https://github.com/hacf-fr/renault-api/issues/48)

**Comment by ErnieB44** [comment]
That explains.. i have the Zoe phase 1. Thanks for the assistance!
