### ISSUE TITLE
last_update value.

### ISSUE THREAD

**Issue by LupoCri** [hacf-fr/hassRenaultZE#79]
Hi.

I would ask if it is possible to re-add the _last_update_ value to the sensors. 

Thanks for the great job.

Cri.

**Comment by epenet** [comment]
Hi

I'm not sure what you mean... last_update is an attribute on all the battery sensors (battery level, remaining range, charge state, etc.)

**Comment by LupoCri** [comment]
Ops...
Sorry...
Tnx for reply.
Ciao,
Cri
