### ISSUE TITLE
Add translations for "SCHEDULE_MODE"

### ISSUE THREAD

**Issue by epenet** [hacf-fr/hassRenaultZE#81]
For the calendar, is it possible to translate "SCHEDULE_MODE" by "Activated", "Activé" in french, and "ALWAYS_CHARGING" by "Deactivated", "Désactivé" in french?

![Capture](https://user-images.githubusercontent.com/41892950/101269529-fd917d00-376f-11eb-9921-9783fa57f9d4.JPG)

_Originally posted by @JeedHome44 in https://github.com/hacf-fr/hassRenaultZE/issues/41#issuecomment-739443737_

**Comment by JeedHome44** [comment]
For french translation is it correct?

```
{
  "state": {
    "renault__plug_state": {
      "unplugged": "Débranché",
      "plugged": "Branché",
      "plug_error": "Erreur prise"
    },
    "renault__charge_state": {
      "not_in_charge": "Pas de charge",
      "waiting_for_planned_charge": "En attente pour la charge programmée",
      "charge_ended": "Charge terminée",
      "waiting_for_current_charge": "En attente du courant de charge",
      "energy_flap_opened": "Trappe de charge ouverte",
      "charge_in_progress": "En charge",
      "charge_error": "Pas de charge ou débranchée"
    },
    "renault__charge_mode": {
      "SCHEDULE_MODE": "Activé",
      "ALWAYS_CHARGING": "Désactivé",
    }
  }
}
```

**Comment by JeedHome44** [comment]
For EN:

```
{
  "state": {
    "renault__plug_state": {
      "unplugged": "Unplugged",
      "plugged": "Plugged in",
      "plug_error": "Plug error"
    },
    "renault__charge_state": {
      "not_in_charge": "Not charging",
      "waiting_for_planned_charge": "Waiting for planned charge",
      "charge_ended": "Charge ended",
      "waiting_for_current_charge": "Waiting for current charge",
      "energy_flap_opened": "Energy flap opened",
      "charge_in_progress": "Charging",
      "charge_error": "Not charging or plugged in"
    },
    "renault__charge_mode": {
      "SCHEDULE_MODE": "Activated",
      "ALWAYS_CHARGING": "Deactivated"
    }
  }
}
```

**Comment by JeedHome44** [comment]
Add in const.py:

**Comment by epenet** [comment]
I think it will be better to use proper names because I hope to see later some more options in the enumeration.
For now, we have already three options (SCHEDULE_MODE / ALWAYS_CHARGING / ALWAYS)

Maybe tomorrow we will also have another for delayed start (you configure the start time, but not the end time)

So I do not like "activated/deactivated" and I would prefer "SCHEDULE_MODE = calendrier" not "SCHEDULE_MODE = activé"

**Comment by epenet** [comment]
@oncleben31 any thoughts on this?

**Comment by JeedHome44** [comment]
j'ai réussi à le faire! ^^

![Capture](https://user-images.githubusercontent.com/41892950/101409991-f76dde80-38de-11eb-8c43-9d0f27051902.PNG)

**Comment by JeedHome44** [comment]
change sensor.py line 23:

`from .const import DOMAIN, DEVICE_CLASS_PLUG_STATE, DEVICE_CLASS_CHARGE_STATE, DEVICE_CLASS_CHARGE_MODE`

add sensor.py line 146

```
    @property
    def device_class(self) -> str:
        """Returning sensor device class"""
        return DEVICE_CLASS_CHARGE_MODE
```


add const.py line 22:

`DEVICE_CLASS_CHARGE_MODE = "renault__charge_mode"`

**Comment by JeedHome44** [comment]
i never see ALWAYS. what situation is it for?

**Comment by PysX** [comment]
ZE50 (all ?) returns “always” when not in schedule mode. see #38

**Comment by JeedHome44** [comment]
ok. I have a Zoe 40. that's why I've never seen it

**Comment by JeedHome44** [comment]
I think "Activated" and "Deactivated" to be fine. And if you add the charge with a specific time, just add: "Activated at HH:MM "

**Comment by PysX** [comment]
To my opinion charge_mode is “always=instantanée” or “schedule_mode=programmée”

**Comment by JeedHome44** [comment]
You can write what you want after doing change like I'm doing

**Comment by oncleben31** [comment]
I like the proposal of @PysX above.
Anyone to work on a PR ?

**Comment by epenet** [comment]
This is from the MyRenault application:
- fr_FR: "Charge instantanée" / "Planning de charge"
- en_GB: "Instant charge" / "Charge planner"
