### ISSUE TITLE
Support hvac-settings and hvac-schedule endpoint

### ISSUE THREAD

**Issue by epenet** [hacf-fr/hassRenaultZE#82]
Once implemented in [renault-api](https://github.com/hacf-fr/renault-api/issues/86), it would be good to add to HomeAssistant...

**Comment by JeedHome44** [comment]
what is it exactly?

**Comment by epenet** [comment]
Air conditioning control and planning - same as charge planning control

**Comment by JeedHome44** [comment]
ok, i have already personally scheduled the Zoe Preconditioning only on school days at 8:15 and the evenings I work at 19:40.

**Comment by epenet** [comment]
⚠️ The Renault integration was originally merged into core in 2021.8 and finalised in 2021.10. The use of this custom component has been deprecated since then and should no longer be used
