### ISSUE TITLE
 Uppercase VIN and MODE + Problem action Calendar On

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#83]
The VIN and the 2 load modes must be capitalized in the scripts to launch actions.

However, I cannot activate the calendar after having successfully deactivated it.
With version 2, it could be activated with the function to return the entire calendar.

**Comment by JeedHome44** [comment]
charge_on never worked but charge_set_schedules did in 2.0.

Is it possible to see what is wrong?
I use these actions a lot when my Zoe starts to charge when I plug it in while the calendar is activated and out of charge schedule

Thank you

**Comment by JeedHome44** [comment]
After a long time, the schedule switched to SCHEDULE_MODE. I will do more tests to see which action to work.

**Comment by JeedHome44** [comment]
Final result:

![Capture](https://user-images.githubusercontent.com/41892950/101283070-af649400-37d8-11eb-995c-1a430a935a33.JPG)

**Comment by JeedHome44** [comment]
I hadn't done a test in the car.  I just made several and here is the result.

Don't work:
Charge_mode on: KO
Charge_mode off: KO
Hvac off: KO

Work:
Hvac on: OK
Calendar_set: OK
Charge_go: OK

I think the problem with charge_mode is the upper case letters in the script.  if I put SCHEDULE_MODE or ALWAYS_CHARGING in lowercase, the script does not work.  But I think we have to send lowercase to Renault.  can you fix this problem?

**Comment by epenet** [comment]
Charge-mode issue is a bug on renault-api: https://github.com/hacf-fr/renault-api/pull/87

**Comment by JeedHome44** [comment]
i haven't really tested hvac off. I clicked on it but it didn't work right away. I may not have waited long enough.

Ok for charge_mode I thought it was because of the caps.

**Comment by JeedHome44** [comment]
everything is working fine for the moment and I have not noticed any stoppage of operation as on version 2. I am waiting to have more days of hindsight to see if something does not work anymore. Good work ;)
