### ISSUE TITLE
slow return states

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#84]
Hello,

is it normal that the return is slow to come back?

can we force a return of state after sending an action?

**Comment by JeedHome44** [comment]
I did tests. When I click to change calendar state, it's really change after 15-20 sec in the car.
But states return to Hassio after 150-300 sec.
It's a real return or just update states all 5 minutes?
It's possible to update cron1?

**Comment by PysX** [comment]
Hello, polling is done all 5min.
Querying under may cause unavailable sensors due to API(Renault side) limitations. See #68 and #75 
With some testing 5min seems ok.

**Comment by epenet** [comment]
I think we can try to put 1 min back in
There was a parrellelism bug in 3.0.0 so maybe now 1 min is OK again.

**Comment by oncleben31** [comment]
Or perhaps we could force a punctual refresh API on certain circonstances. This case seems appropriate for that.

**Comment by JeedHome44** [comment]
I tried this morning to put 2 minutes on the scan interval and the renault server did not want me to connect.
it is therefore surely impossible to go below 5 minutes

**Comment by epenet** [comment]
So we'll need to implement the recommendation from @oncleben31 ... who wants to work on PR?

**Comment by JeedHome44** [comment]
hello,
you mean, contact renault to ask them to drop to 1 minute? That would be great!

**Comment by JeedHome44** [comment]
or knowing that the real state of the calendar changes about 10-15 seconds after the action, would it be possible to do a refresh 30 sec after the action on the calendar?

**Comment by epenet** [comment]
No, it's changing the custom component so that after a "set" request then an extra "get" request is added right away (or after xx seconds)

**Comment by JeedHome44** [comment]
ok, so we should put a get request 30 sec after a set

**Comment by JeedHome44** [comment]
if I knew how to do it, I would have done it right away, but this is beyond my reach. I have to take python lessons ^^

**Comment by JeedHome44** [comment]
we have to add this after each action in the file renault_vehicle.py?
or it's more difficult?

```
                # Polling interval. Will only be polled if there are subscribers.
                update_interval=DEFAULT_SCAN_INTERVAL,
```

**Comment by Jastroger** [comment]
My Zoe is not updating after 5mins. My wife is currently loading the car in the city - there were no updates since she left. 55% battery when she left, now she said its about 89%. In Home Assistant lovelace card its still 55% and not plugged in. 

Is there any chance to update this manually?

**Comment by PysX** [comment]
Asking a refresh after an action is a good idea but not sure of the result. I tried to measure time between starting AC service call and the car flashing. It’s varying ... 10s to   55s (Five measures). It may depend connections between my phone to my HA to Renault server to the car).
