### ISSUE TITLE
Add time unit

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#85]
Can you add time unit here?

```
class RenaultChargingRemainingTimeSensor(RenaultBatteryDataEntity):
    """Charging Remaining Time sensor."""

    @property
    def state(self) -> Optional[int]:
        """Return the state of this entity."""
        return self.data.chargingRemainingTime
```

With:

add sensor.py line 16:

`    TIME_MINUTES,`

add sensor.py line 160:

```
    @property
    def unit_of_measurement(self) -> str:
        """Return the unit of measurement of this entity."""
        return TIME_MINUTES
```

**Comment by JeedHome44** [comment]
it's ok!

![Capture](https://user-images.githubusercontent.com/41892950/101412960-be843880-38e3-11eb-8083-3cb4a3ff5652.PNG)

**Comment by theneedyguy** [comment]
Easiest way to get this into the project would be to create a pull request.

**Comment by epenet** [comment]
@JeedHome44 since you have already done the work, maybe you can provide a PR?

**Comment by JeedHome44** [comment]
yes I would like but I never did. can someone explain to me how to do a PR?

**Comment by theneedyguy** [comment]
In the easiest terms: You fork this repo, make the changes on your fork then you make a pull request by clicking the link where it says "Pull Request" on your repo. The link is located below the green "Code" button. Hope this helped.

**Comment by epenet** [comment]
There is also this guide for development in VisualStudioCode inside a container: https://hacs.xyz/docs/developer/devcontainer

And you get get some help from the [hacf team](https://hacf.fr/) on [Discord](https://discord.com/invite/PaZFEjX)

**Comment by JeedHome44** [comment]
I did well like that?

**Comment by epenet** [comment]
Yes, very good...

One small notes:
- add "Closes #xxx" in the initial commentary with xxx replaced by the issue ID that it is related to (I changed it for you)

**Comment by theneedyguy** [comment]
Well done! Congratz on your first contribution to an OSS project. A part of you now will live in every active instance of this custom component. It might not seem like much but every tiny bit helps improve this project.
