### ISSUE TITLE
Charge_mode on/off fails

### ISSUE THREAD

**Issue by epenet** [hacf-fr/hassRenaultZE#87]
Don't work:
Charge_mode on: KO > need lowercase
Charge_mode off: KO > need lowercase
Hvac off: KO > never work

Work:
Hvac on: OK
Calendar_set: OK > Activ Cal
Charge_go: OK > Deactiv Cal

I think the problem with charge_mode is the upper case letters in the script.  if I put SCHEDULE_MODE or ALWAYS_CHARGING in lowercase, the script does not work.  But I think we have to send lowercase to Renault.  can you fix this problem?

_Originally posted by @JeedHome44 in https://github.com/hacf-fr/hassRenaultZE/issues/83#issuecomment-739551495_

**Comment by epenet** [comment]
Charge-mode issue is a bug on renault-api which will be fixed in the next release: hacf-fr/renault-api#87
Do you have some traces to show if the Renault servers accepted the bad values or if they were rejected?

**Comment by epenet** [comment]
@JeedHome44 renault-api is updated to v0.0.3.
Do you want to provide a PR to bump the renault-api version here ?

**Comment by JeedHome44** [comment]
I made the other change by inference but I don't know how to do this one.  I let you do it.  😉

**Comment by epenet** [comment]
It's a good exercise for you also... for this you only need to update the manifest file:
https://github.com/hacf-fr/hassRenaultZE/blob/master/custom_components/renault/manifest.json

**Comment by JeedHome44** [comment]
Ok i will test 😉

**Comment by JeedHome44** [comment]
Close #88

**Comment by epenet** [comment]
You have to add comment on the PR to close the Issue (not a comment on the issue to close the PR)

**Comment by JeedHome44** [comment]
like that?
