### ISSUE TITLE
Add Info sensor: Last get request to renault server

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#91]
hello,

is it possible to have an information in a sensor which displays the date and time of the last consultation of the renault server?
that would allow to see at a glance if the info of such or such sensor is up to date or not.

in version 2.0 there was this information. I see that it is assigned in 2 different sensors but it is not the same value for the 2. Why? and it doesn't really show the last home assistant check.

**Comment by epenet** [comment]
This is not a problem of this custom component, nor a problem of renault-api package.
The timestamp in the attributes is the timestamp of the last update from the Renault vehicle to the Renault servers (not the timestamp of the last query from HomeAssistant to the Renault servers.

If you look at this folder (https://github.com/hacf-fr/renault-api/tree/main/tests/fixtures/kamereon/vehicle_data ) you will see that only `battery-status` and `location` provide a timestamp, all the other endpoints do not provide this information.

You can provide a PR to add "last queried" information, but it needs to be kept separate from the "server timestamp" and I am not sure it's really useful.

**Comment by JeedHome44** [comment]
in fact i just want to know when the Home assistant sends a request to the Renault server.  I'm not talking about the info Renault provides.
