### ISSUE TITLE
Disconnect frequently

### ISSUE THREAD

**Issue by flouck** [hacf-fr/hassRenaultZE#94]
## Describe the bug
All sensors related to the Renault integration disconnect frequently. And display unavailable while being disconnected. Please see on the screenshots:
![image](https://user-images.githubusercontent.com/60158607/101988052-c2270f00-3c97-11eb-9196-5c715f1a995f.png)
![image](https://user-images.githubusercontent.com/60158607/101988109-0c0ff500-3c98-11eb-8296-52cf07117995.png)
![image](https://user-images.githubusercontent.com/60158607/101988124-1fbb5b80-3c98-11eb-833b-b826c844d371.png)

I do have the latest version v3.0.2 (no update available in HACS). I tried reloading the integration. What is suprising is that with the former way (writing in the yaml file), it still works fine:

![image](https://user-images.githubusercontent.com/60158607/101988184-585b3500-3c98-11eb-99da-325df9278cfa.png)

**Comment by flouck** [comment]
Logs : 

```
Logger: homeassistant.loader
Source: loader.py:465
First occurred: 4:40:53 PM (1 occurrences)
Last logged: 4:40:53 PM
You are using a custom integration for renault which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant. 


Logger: custom_components.renault.renault_vehicle
Source: helpers/update_coordinator.py:166
Integration: Renault (documentation, issues)
First occurred: 4:42:40 PM (2 occurrences)
Last logged: 4:47:52 PM

    Error fetching VF1xxx hvac_status data: This endpoint has been disabled: ('err.func.403', 'Operation not supported Operation not supported for this can (C1A)')
    Error fetching VF1xxx battery data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.')


Logger: homeassistant.config_entries
Source: custom_components/renault/renault_vehicle.py:33
First occurred: 4:50:23 PM (1 occurrences)
Last logged: 4:50:23 PM
Error setting up entry Zoe for renault

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renault/__init__.py", line 34, in async_setup_entry
    await renault_hub.set_account_id(config_entry.data[CONF_KAMEREON_ACCOUNT_ID])
  File "/config/custom_components/renault/renault_hub.py", line 47, in set_account_id
    vehicle = RenaultVehicleProxy(
  File "/config/custom_components/renault/renault_vehicle.py", line 33, in __init__
    "identifiers": {(DOMAIN, details.vin)},
AttributeError: 'NoneType' object has no attribute 'vin'
```

_I modified the VIN number for privacy concerns._

**Comment by epenet** [comment]
@flouck which version of the component are you using? There was an issue in a previous version with too many calls overloading the Renault servers.

I also suggest that you turn on more advanced logging using these settings:
```
logger:
  default: error
  logs:
    renault_api: debug
    custom_components.renault: debug
```

**Comment by epenet** [comment]
Also, I have just found a comment @Jastroger on https://github.com/hacf-fr/hassRenaultZE/issues/84#issuecomment-743779964, at about the same time as your issues, that indicates there were issues on the Renault servers around that time.

Can you please confirm if it is still an issue for you?

**Comment by PysX** [comment]
I confirm same problem 4 days ago (`Failed to forward request to remote service `). « My Renault » app was KO too. So Renault side!

**Comment by flouck** [comment]
Indeed it works now. Thank you!
