### ISSUE TITLE
sensor.zoe_range

### ISSUE THREAD

**Issue by kamcioo** [hacf-fr/hassRenaultZE#97]
Hello,

since ca. two weeks don’t work the “range” anymore. Other sensors (that I use) work fine.
In the logbook I can’t find any entries.

## Version of the custom_component
3.0.3

**Comment by epenet** [comment]
I have just now updated the release notes for v3.0.2
https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2

With the added support of fuel vehicles, the `Range` sensor was renamed `Battery Autonomy`

Can you check if that sensor appears correctly?

**Comment by kamcioo** [comment]
Hi,

thank You for the quick reply.

It was my idea, that perhaps the sensor has now new name but why battery autonomy? Why not for example battery_range? It would be more easier for people that are not so good in such things ;-)
Yes, with autonomy appears the sensor (Renault Zoe) correctly. Thank You for Your help and great Add-on.

PS. Perhaps it ist not correct, that I write it here but it would be very helpful, when You somewhere writes, which sensors which variable give. For example I have tried to do a automation, that I get a info, when my zoe by charging send me a message by 99%. It works when I made it only with the percentage. I would also make a condition that I get the message only by charging. I don’t know what should I write by state. Charging/yes/true? A table with possibly states would be very helpful.

**Comment by epenet** [comment]
The reason for the name is to keep it in line with the underlying Renault API.

Regarding the states for charging status, it depends which sensor you use.
- Binary sensors (`binary_sensor.xxx_charging` and `binary_sensor.xxx_plugged_in`) should be binary values
- Regular sensors (`sensor.xxx_plug_state` and `sensor.xxx_charge_state`) uses `slug` from `PlugState` and `ChargeState` in https://github.com/hacf-fr/renault-api/blob/main/src/renault_api/kamereon/enums.py

You can also see the `slugs` in https://github.com/hacf-fr/hassRenaultZE/blob/master/custom_components/renault/translations/sensor.en.json
