### ISSUE TITLE
Charging Power not plausible for ZE50

### ISSUE THREAD

**Issue by rdu** [hacf-fr/hassRenaultZE#98]
Hello,

the values the system reports for the charging power is not plausible.

The ZE50 is able to charge with a maximum at 50KW when using DC and a maximum at 22KW when using AC.

![Bildschirmfoto von 2020-12-28 10-09-11](https://user-images.githubusercontent.com/445462/103203235-c6d4ff80-48f4-11eb-88e4-a0a1ae768784.png)

The first 3 spikes are DC charging the last is AC charging.

**Comment by epenet** [comment]
Hi @rdu,

Please read this page: https://github.com/hacf-fr/renault-api/wiki/Data-endpoint:-battery-status.
The data comes directly from the Renault servers, and is known to be reliable on ZE40 (in Watts), but unreliable on ZE50 (seemingly in KiloWatts). As far as I am aware, no-one has managed to figure out a formula for converting the Renault Server values into reasonable values.

If you find a formula for getting valid values, then I encourage you to open a PR on https://github.com/hacf-fr/renault-api

**Comment by Meph79** [comment]
Been following this value during charging (Have ZE50) this value seems not to be actual charging power but the "Max allowed charging power that the battery can take" .. Is this also true for ZE40? It seems to be correct for ZE50 in that aspect...

**Comment by rdu** [comment]
That sounds plausible.


That would mean: if value > than "max station power" then value = "max station power", if value < "max station power" then value is valid.

Too bad we do not know the "max station power"

**Comment by theneedyguy** [comment]
@rdu If you have a charging station with an API that exposes these values you could theoretically make your own template sensor. This would only work when charging at home unfortunately. Just and idea.

**Comment by rdu** [comment]
I close the issue due to cause of the underlying library.
